#
# Copyright © 2016-2026 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

#test push

name: ThingsBoard CI

on: 
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ] #ici par exemple

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: thingsboard
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          fetch-depth: 0 

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and install all modules
        run: mvn clean install -DskipTests

      - name: Run unit tests
        run: >
          mvn test
          -pl='!application,!dao,!ui-ngx,!msa/js-executor,!msa/web-ui,!netty-mqtt'

      - name: Test new feature EntityNameValidator
        run: mvn test -Dtest=EntityNameValidatorTest -pl common/util

      - name: Initialize PostgreSQL database
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d thingsboard -c "
            DO \$\$ 
            BEGIN
              IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'root') THEN
                CREATE ROLE root WITH LOGIN SUPERUSER PASSWORD 'postgres';
              END IF;
            END
            \$\$;
          "
        env:
          PGPASSWORD: postgres

      - name: Launch ThingsBoard
        run: |
          JAR=$(find application/target -name "thingsboard-*.jar" | head -n 1)

          java -jar "$JAR" \
            --spring.datasource.url=jdbc:postgresql://localhost:5432/thingsboard \
            --spring.datasource.username=postgres \
            --spring.datasource.password=postgres &

          sleep 60
